name = "ZeusTools"
author = "WSV-Team"
mainprefix = "z"
prefix = "ZT"

[files]
include = [
    "zt_logo.paa",
]

[version]
major = 0
minor = 1
patch = 0
build = 0

[build]
main_addon = ["addons/debug", "addons/Sequencer", "addons/edenplus"]
